stages:
  - package

package:debug:
  stage: package
  image: thyrlian/android-sdk
  variables: {}
  script:
    - ./gradlew --no-daemon :app:assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/*.apk
    expire_in: 1 week

package:release:
  stage: package
  image: thyrlian/android-sdk
  script:
    - echo "apiSecret=${FABRIC_API_SECRET}" > app/fabric.properties
    - ./gradlew --no-daemon :app:assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/release/*.apk
  only:
    - master