stages:
  - package

package:
  stage: package
  image: thyrlian/android-sdk
  script:
    - ./gradlew :app:assemble
  artifacts:
    paths:
      - app/build/outputs/apk/debug/*.apk
      - app/build/outputs/apk/release/*.apk
    expire_in: 1 week