version: '3'
services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3316:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=demopass
      - MYSQL_DATABASE=c2s
    restart: always
  dns:
    build: ./dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: always