# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

skip_docs

default_platform(:android)

platform :android do

  desc "Prep release"
  lane :prep_release do |options|
    ensure_git_status_clean

    version_name = android_get_version_name
    version_code = android_get_version_code

    # create changelog meta data
    changelog_contents = read_changelog
    android_changelogs_dir_path = 'metadata/android/changelogs/en-US'
    android_changelog_file_path = "#{android_changelogs_dir_path}/#{version_code}.txt"
    FileUtils.mkdir_p(android_changelogs_dir_path)
    FileUtils.touch(android_changelog_file_path)
    File.write(android_changelog_file_path, changelog_contents)

    stamp_changelog(
      section_identifier: version_name
    )

    git_commit(
      'path': [android_changelog_file_path, 'CHANGELOG.md'],
      'message': "Version: #{version_name}"
    )

    add_git_tag(
      tag: "v#{version_name}"
    )

    # bump version number
    next_version_code = (version_code.to_i + 1).to_s
    next_version_name = next_version_code
        .match(/([0-9]{1})([0-9]{3})([0-9]{3})$/)
        .captures.map { |v| v.to_i(10) }
        .join('.')

    android_set_version_name(version_name: next_version_name)
    android_set_version_code(version_code: next_version_code)

    git_commit(
      'path': ['app/build.gradle'],
      'message': "Bump version to #{next_version_name}"
    )

    # push changes

    push_to_git_remote
    push_git_tags
  end

  desc "Publish Beta to Google Play Store"
  lane :publish_beta do |options|
    ensure_git_status_clean

    version_name = android_get_version_name
    version_code = android_get_version_code

    upload_to_play_store(
      json_key: options[:gps_key_path],
      apk: options[:apk_path],
      track: 'beta',
    )
  end
end