# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

skip_docs

default_platform(:android)

platform :android do

  desc "Beta release to Google Play Store"
  lane :beta do |options|

    ensure_git_status_clean

    upload_to_play_store(
        json_key: options[:gps_key_path],
        apk: options[:apk_path],
        track: 'beta'
    )
  end

  lane :release do |options|
    version_name = android_get_version_name

    stamp_changelog(
      section_identifier: version_name
    )
  end
end